name: Run TestNG Tests

on:
  push:
    branches: [ "main" ]   # change to "master" if your branch is master
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest   # you can also use ubuntu-latest if you prefer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run TestNG Tests
        run: mvn clean test -DsuiteXmlFile=testng.xml
